SELECT (SUM(TOTAL_QUANTITY)) as TOTAL
      ,(SUM(TOTAL_QUANTITY) - SUM(RESERVED_QUANTITY) - SUM(RESERVED_QUANTITY_SNAPSHOT) + SUM(ADJUSTMENT_QUANTITY) + SUM(ADJUSTMENT_QUANTITY_SNAPSHOT)) as AVAILABLE
      ,TO_CHAR((MAX(LAST_UPDATE)),'DD-MON-YY HH24:MI:SS') as LAST_STOCK_UPDATE_DATE
      ,PRODUCT_IDENTIFIER 
      ,COLOUR_ID
      ,COMPUTER_SIZE_NUMBER
      ,LOCATION_ARVATO
FROM ECOMHUB.STOCK
WHERE PRODUCT_IDENTIFIER = '2137968' GROUP BY PRODUCT_IDENTIFIER, COLOUR_ID, COMPUTER_SIZE_NUMBER, LOCATION_ARVATO ORDER BY LAST_STOCK_UPDATE_DATE DESC;